import type { Recipe } from '@/types';

export const sampleRecipes: Recipe[] = [
  {
    id: 'seed-1',
    title: 'Overnight Oats',
    description: 'Creamy oats packed with fruit and nuts — ready when you wake up.',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'kid-approved'],
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 2,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Rolled oats', quantity: 1, unit: 'cup' },
      { id: 'i2', name: 'Milk', quantity: 1, unit: 'cup' },
      { id: 'i3', name: 'Chia seeds', quantity: 2, unit: 'tbsp' },
      { id: 'i4', name: 'Honey', quantity: 1, unit: 'tbsp' },
      { id: 'i5', name: 'Blueberries', quantity: 0.5, unit: 'cup' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Combine oats, milk, and chia seeds in a jar.' },
      { stepNumber: 2, instruction: 'Add honey and stir well.' },
      { stepNumber: 3, instruction: 'Refrigerate overnight (at least 4 hours).' },
      { stepNumber: 4, instruction: 'Top with blueberries and serve cold.' },
    ],
    nutrition: { calories: 320, proteinG: 11, carbsG: 52, fatG: 7 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-2',
    title: 'Sheet Pan Chicken & Veggies',
    description: 'One-pan wonder with juicy chicken thighs and roasted vegetables.',
    mealTypes: ['dinner'],
    tags: ['gluten-free', 'dairy-free', 'high-protein'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    servings: 4,
    isFavorite: true,
    ingredients: [
      { id: 'i1', name: 'Chicken thighs', quantity: 4, unit: 'pieces' },
      { id: 'i2', name: 'Broccoli florets', quantity: 2, unit: 'cups' },
      { id: 'i3', name: 'Bell peppers', quantity: 2, unit: 'pieces' },
      { id: 'i4', name: 'Olive oil', quantity: 3, unit: 'tbsp' },
      { id: 'i5', name: 'Garlic powder', quantity: 1, unit: 'tsp' },
      { id: 'i6', name: 'Paprika', quantity: 1, unit: 'tsp' },
      { id: 'i7', name: 'Salt & pepper', quantity: 1, unit: 'pinch' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Preheat oven to 425°F (220°C).' },
      { stepNumber: 2, instruction: 'Toss chicken and veggies with oil and spices on a sheet pan.' },
      { stepNumber: 3, instruction: 'Roast for 30–35 min until chicken is cooked through.' },
    ],
    nutrition: { calories: 420, proteinG: 38, carbsG: 12, fatG: 24 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-3',
    title: 'Quick Black Bean Tacos',
    description: 'Weeknight-fast vegetarian tacos the whole family loves.',
    mealTypes: ['lunch', 'dinner'],
    tags: ['vegetarian', 'kid-approved', 'dairy-free'],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 4,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Flour tortillas', quantity: 8, unit: 'pieces' },
      { id: 'i2', name: 'Black beans', quantity: 1, unit: 'can', notes: 'drained' },
      { id: 'i3', name: 'Corn', quantity: 0.5, unit: 'cup' },
      { id: 'i4', name: 'Salsa', quantity: 0.5, unit: 'cup' },
      { id: 'i5', name: 'Cumin', quantity: 1, unit: 'tsp' },
      { id: 'i6', name: 'Avocado', quantity: 1, unit: 'piece' },
      { id: 'i7', name: 'Fresh lime', quantity: 1, unit: 'piece' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Heat beans with cumin and corn in a pan for 5 min.' },
      { stepNumber: 2, instruction: 'Warm tortillas on a dry skillet.' },
      { stepNumber: 3, instruction: 'Fill tortillas and top with salsa, avocado, and lime.' },
    ],
    nutrition: { calories: 310, proteinG: 12, carbsG: 48, fatG: 9 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-4',
    title: 'Greek Salad with Grilled Salmon',
    description: 'Light and fresh lunch with omega-3 rich salmon.',
    mealTypes: ['lunch'],
    tags: ['gluten-free', 'high-protein', 'low-carb'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 2,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Salmon fillets', quantity: 2, unit: 'pieces' },
      { id: 'i2', name: 'Romaine lettuce', quantity: 4, unit: 'cups' },
      { id: 'i3', name: 'Cherry tomatoes', quantity: 1, unit: 'cup' },
      { id: 'i4', name: 'Cucumber', quantity: 1, unit: 'piece' },
      { id: 'i5', name: 'Feta cheese', quantity: 0.5, unit: 'cup' },
      { id: 'i6', name: 'Kalamata olives', quantity: 0.25, unit: 'cup' },
      { id: 'i7', name: 'Olive oil', quantity: 2, unit: 'tbsp' },
      { id: 'i8', name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Season salmon with olive oil, salt, and pepper. Grill 4-5 min per side.' },
      { stepNumber: 2, instruction: 'Chop salad vegetables and combine.' },
      { stepNumber: 3, instruction: 'Dress salad with olive oil and lemon. Top with flaked salmon.' },
    ],
    nutrition: { calories: 380, proteinG: 42, carbsG: 8, fatG: 20 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-5',
    title: 'Banana Pancakes',
    description: '2-ingredient fluffy pancakes kids will flip for.',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'gluten-free', 'dairy-free', 'kid-approved'],
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    isFavorite: true,
    ingredients: [
      { id: 'i1', name: 'Ripe bananas', quantity: 2, unit: 'pieces' },
      { id: 'i2', name: 'Eggs', quantity: 2, unit: 'pieces' },
      { id: 'i3', name: 'Maple syrup', quantity: 2, unit: 'tbsp', notes: 'to serve' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mash bananas well and mix in eggs until smooth.' },
      { stepNumber: 2, instruction: 'Cook small pancakes on medium heat for 2-3 min per side.' },
      { stepNumber: 3, instruction: 'Serve with maple syrup.' },
    ],
    nutrition: { calories: 210, proteinG: 8, carbsG: 36, fatG: 5 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-6',
    title: 'Beef & Vegetable Stir Fry',
    description: 'Quick weeknight dinner with tender beef strips and crunchy veg.',
    mealTypes: ['dinner'],
    tags: ['dairy-free', 'high-protein'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 4,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Beef sirloin', quantity: 500, unit: 'g', notes: 'thinly sliced' },
      { id: 'i2', name: 'Mixed stir-fry vegetables', quantity: 3, unit: 'cups' },
      { id: 'i3', name: 'Soy sauce', quantity: 3, unit: 'tbsp' },
      { id: 'i4', name: 'Sesame oil', quantity: 1, unit: 'tbsp' },
      { id: 'i5', name: 'Ginger', quantity: 1, unit: 'tsp', notes: 'grated' },
      { id: 'i6', name: 'Garlic', quantity: 2, unit: 'cloves' },
      { id: 'i7', name: 'Cooked rice', quantity: 2, unit: 'cups', notes: 'to serve' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Heat wok over high heat. Stir fry beef until browned, 3-4 min. Set aside.' },
      { stepNumber: 2, instruction: 'Stir fry garlic and ginger 30 sec, then add vegetables 3-4 min.' },
      { stepNumber: 3, instruction: 'Return beef, add soy sauce and sesame oil, toss and serve over rice.' },
    ],
    nutrition: { calories: 450, proteinG: 34, carbsG: 38, fatG: 16 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-7',
    title: 'Veggie-Packed Pasta Bake',
    description: 'Make-ahead pasta that feeds the whole family and reheats beautifully.',
    mealTypes: ['dinner'],
    tags: ['vegetarian', 'kid-approved'],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 6,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Penne pasta', quantity: 400, unit: 'g' },
      { id: 'i2', name: 'Marinara sauce', quantity: 700, unit: 'ml' },
      { id: 'i3', name: 'Zucchini', quantity: 1, unit: 'piece', notes: 'diced' },
      { id: 'i4', name: 'Spinach', quantity: 2, unit: 'cups' },
      { id: 'i5', name: 'Mozzarella', quantity: 200, unit: 'g', notes: 'shredded' },
      { id: 'i6', name: 'Parmesan', quantity: 50, unit: 'g', notes: 'grated' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook pasta to al dente. Preheat oven to 400°F (200°C).' },
      { stepNumber: 2, instruction: 'Combine pasta, sauce, zucchini, and spinach in a baking dish.' },
      { stepNumber: 3, instruction: 'Top with mozzarella and parmesan. Bake 25-30 min until bubbly.' },
    ],
    nutrition: { calories: 380, proteinG: 18, carbsG: 54, fatG: 12 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-8',
    title: 'Smoothie Bowl',
    description: 'Vibrant frozen fruit bowl with toppings kids love to customize.',
    mealTypes: ['breakfast'],
    tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'kid-approved'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    servings: 2,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Frozen mixed berries', quantity: 2, unit: 'cups' },
      { id: 'i2', name: 'Frozen banana', quantity: 1, unit: 'piece' },
      { id: 'i3', name: 'Almond milk', quantity: 0.25, unit: 'cup' },
      { id: 'i4', name: 'Granola', quantity: 0.5, unit: 'cup', notes: 'to top' },
      { id: 'i5', name: 'Sliced strawberries', quantity: 0.5, unit: 'cup', notes: 'to top' },
      { id: 'i6', name: 'Coconut flakes', quantity: 2, unit: 'tbsp', notes: 'to top' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Blend frozen berries, banana, and almond milk until very thick.' },
      { stepNumber: 2, instruction: 'Pour into bowls and add toppings.' },
    ],
    nutrition: { calories: 260, proteinG: 5, carbsG: 54, fatG: 4 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-9',
    title: 'Lentil Soup',
    description: 'Hearty, protein-rich soup that makes a week of lunches.',
    mealTypes: ['lunch', 'dinner'],
    tags: ['vegetarian', 'vegan', 'gluten-free', 'dairy-free', 'high-protein'],
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    servings: 6,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Red lentils', quantity: 2, unit: 'cups' },
      { id: 'i2', name: 'Diced tomatoes', quantity: 1, unit: 'can' },
      { id: 'i3', name: 'Onion', quantity: 1, unit: 'piece', notes: 'diced' },
      { id: 'i4', name: 'Carrots', quantity: 2, unit: 'pieces', notes: 'diced' },
      { id: 'i5', name: 'Cumin', quantity: 2, unit: 'tsp' },
      { id: 'i6', name: 'Vegetable broth', quantity: 6, unit: 'cups' },
      { id: 'i7', name: 'Spinach', quantity: 2, unit: 'cups' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Sauté onion and carrots 5 min. Add cumin and cook 1 min.' },
      { stepNumber: 2, instruction: 'Add lentils, tomatoes, and broth. Bring to boil then simmer 25 min.' },
      { stepNumber: 3, instruction: 'Stir in spinach until wilted. Season to taste.' },
    ],
    nutrition: { calories: 280, proteinG: 18, carbsG: 44, fatG: 2 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
  {
    id: 'seed-10',
    title: 'Avocado Toast with Egg',
    description: 'Classic crowd-pleaser ready in 10 minutes.',
    mealTypes: ['breakfast', 'lunch'],
    tags: ['vegetarian', 'kid-approved'],
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    servings: 2,
    isFavorite: false,
    ingredients: [
      { id: 'i1', name: 'Whole grain bread', quantity: 4, unit: 'slices' },
      { id: 'i2', name: 'Avocados', quantity: 2, unit: 'pieces' },
      { id: 'i3', name: 'Eggs', quantity: 4, unit: 'pieces' },
      { id: 'i4', name: 'Lemon juice', quantity: 1, unit: 'tbsp' },
      { id: 'i5', name: 'Red pepper flakes', quantity: 0.5, unit: 'tsp', notes: 'optional' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Toast bread. Mash avocado with lemon, salt, and pepper.' },
      { stepNumber: 2, instruction: 'Fry or poach eggs to your liking.' },
      { stepNumber: 3, instruction: 'Spread avocado on toast, top with egg and red pepper flakes.' },
    ],
    nutrition: { calories: 380, proteinG: 16, carbsG: 28, fatG: 24 },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    source: 'manual',
  },
];
